name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build Windows
      run: env GOOS=windows GOARCH=amd64 go build -o ./aivle-cli-windows-amd64.exe

    - name: Build Linux
      run: env GOOS=linux GOARCH=amd64 go build -o ./aivle-cli-linux-amd64
      
    - uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./aivle-cli-*
